[scylladb]
uri = "127.0.0.1:9042"
init_path = "config/init.cql"

[channels]
raw_buffer = 4096
normalized_buffer = 4096
control_buffer = 8
log_buffer = 10000

[binance]
exchange_info = "https://api2.binance.com/api/v3/exchangeInfo?permissions=SPOT"
snapshot = "https://api.binance.com/api/v3/depth"
ws = "wss://stream.binance.com:443/ws"
max_subscription_per_ws = 50

[bitget]
exchange_info = "https://api.bitget.com/api/v2/spot/public/symbols"
ws = "wss://ws.bitget.com/v2/ws/public"
max_subscription_per_ws = 50

[bybit]
exchange_info = "https://api.bybit.com/v5/market/instruments-info?category=spot"
ws = "wss://stream.bybit.com/v5/public/spot"
max_subscription_per_ws = 10

[coinbase]
exchange_info = "https://api.coinbase.com/api/v3/brokerage/market/products"
ws = "wss://ws-feed.exchange.coinbase.com"
max_subscription_per_ws = 50

[kraken]
exchange_info = "https://api.kraken.com/0/public/AssetPairs"
ws = "wss://ws.kraken.com/v2"
max_subscription_per_ws = 50

[okx]
exchange_info = "https://www.okx.com/api/v5/public/instruments?instType=SPOT"
ws = "wss://ws.okx.com:8443/ws/v5/public"
max_subscription_per_ws = 50